server:
  port: 8081

logging:
  level:
    com.example.meetbefore: DEBUG
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
#  config-location: classpath:/mybatis-config.xml

#spring:
#  application:
#    name: meetbefore
#  datasource: #这是MySQL所使用的配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/collect?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: Wm123456



#这是mybatis所使用的配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
#  使用mybatis有两个重要的配置：1:mapper-locations:告诉mybatisSQL的映射文件在这里
#  2:type-aliases-package:告诉mybatis对应的实体类位置
# 如果使用mybatis-plus 就不能再用 上面那个配置了

#这是mybatis-plus所使用的配置
#mybatis-plus:
#  mapper-locations: classpath:/*.xml  报错 因为里面有其他配置文件

